### ISSUE TITLE
Multisig join never resolves

### ISSUE THREAD

**Issue by daviddm** [WebOfTrust/signify-ts#227]
I've made a test where I try to add a third member to a already existing multisig with 2 members.
When the third member tries to join the multisig the join-operation never resolves.

https://github.com/WebOfTrust/signify-ts/commit/4b7bd582572785ca7f073ccab8064051e5b42ef6#diff-4b7bd582572785ca7f073ccab8064051e5b42ef6

**Comment by 2byrds** [comment]
From our keri dev meeting, Provenant along with @pfeairheller recently added two people to their 'migrated' wallet (command line to signify/keria). Signifypy has a series of scripts to test this functionality (for the migration). Provenant did use signify-ts for the two new participants. This was a delegated multi-sig that required approval.
Supplying versions is helpful in order to determine where the fix is needed.
Possibly a signify-ts update has the fix. Or an improvement in the steps used.
Join functionality specifically.

**Comment by Sotatek-HocNguyena** [comment]
Hi @daviddm. Were you able to call the `groups().join`? When I called it, it threw me a "500 Internal Server Error" everytime.

**Comment by daviddm** [comment]
I updated the test and made a PR with it https://github.com/WebOfTrust/signify-ts/pull/255

When running the tests the member that tries to join the multisig-group is able to do it and can add the agent end-role after "successful" join. However the join operation still does not resolve.

I'm not sure if something has changed since February, but I know that i didn't try to just disregard the operation status and continue as if it was successful.

So maybe this isn't a signify-ts issue but instead a keria issue?

## Versions
Keria: 0.1.3
Signify-ts: latest-main fddaff2

**Comment by 2byrds** [comment]
Thank you for the additions! I'll be taking a look at this next week if it hasn't been addressed by then

**Comment by lenkan** [comment]
I tried fixing that line and run against a local keria image, then it resolves. https://github.com/WebOfTrust/keria/pull/236

**Comment by lenkan** [comment]
This will be resolved once we can merge https://github.com/WebOfTrust/signify-ts/pull/258

**Comment by 2byrds** [comment]
@daviddm can this be closed now per https://github.com/WebOfTrust/signify-ts/pull/258 ?

**Comment by lenkan** [comment]
@2byrds Yes, thanks for notifying.
